feat: pile move fail if path is invalid

diff --git a/system/system-rewrite b/system/system-rewrite
--- a/system/system-rewrite
+++ b/system/system-rewrite
@@ -24,6 +24,20 @@ case "$op" in
         ;;
 esac
 
+case "$src" in
+    /*|*..*)
+        echo "ERROR: invalid source path"
+        exit 1
+        ;;
+esac
+
+case "$dst" in
+    /*|*..*)
+        echo "ERROR: invalid destination path"
+        exit 1
+        ;;
+esac
+
 SRC="/$PILE/$src"
 DST="/$PILE/$dst"
 
